/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
sequenceable OHOS.IRemoteObject;
sequenceable cloud_disk_common..OHOS.FileManagement.CloudDiskService.ChangesResult;
sequenceable cloud_disk_common..OHOS.FileManagement.CloudDiskService.FileSyncState;
sequenceable cloud_disk_common..OHOS.FileManagement.CloudDiskService.FailedList;
sequenceable cloud_disk_common..OHOS.FileManagement.CloudDiskService.ResultList;

interface OHOS.FileManagement.CloudDiskService.ICloudDiskService
{
    void RegisterSyncFolderChangesInner([in] String syncFolder, [in] IRemoteObject remoteobject);
    void UnregisterSyncFolderChangesInner([in] String syncFolder);
    ChangesResult GetSyncFolderChangesInner([in] String syncFolder, [in] unsigned long count, [in] unsigned long startUSN);
    List<FailedList> SetFileSyncStatesInner([in] String syncFolder, [in] List<FileSyncState> fileSyncStates);
    List<ResultList> GetFileSyncStatesInner([in] String syncFolder, [in] List<String> pathArray);
    void RegisterSyncFolderInner([in] int userId, [in] String bundleName, [in] String path);
    void UnregisterSyncFolderInner([in] int userId, [in] String bundleName, [in] String path);
    void UnregisterForSaInner([in] String path);
}
